openapi: "3.0.3"
info:
  title: Health Tracker RESTful API
  description: "API Spec for Health Tracker RESTful API"
  version: "1.0"
servers:
  - url: https://localhost:3108/api
paths:
  /users:
    get:
      security:
        - Auth: []
      tags:
        - "User API"
      description: "List all users"
      summary: "List all users"
      responses:
        "200":
          description: "Success get all users"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  code:
                    type: "number"
                  status:
                    type: "string"
                  data:
                    type: "array"
                    items:
                      $ref: "#/components/schemas/User"
    post:
      security:
        - Auth: []
      tags:
        - "User API"
      description: "Create new User"
      summary: "Create new User"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCreateOrUpdate"
      responses:
        "200":
          description: "Success create User"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  code:
                    type: "number"
                  status:
                    type: "string"
                  data:
                    $ref: "#/components/schemas/User"
  /users/{UserId}:
    get:
      security:
        - Auth: []
      tags:
        - "User API"
      description: "Get User by id"
      summary: "Get User by id"
      parameters:
        - name: "UserId"
          in: "path"
          description: "User Id"
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "Success get user"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  code:
                    type: "number"
                  status:
                    type: "string"
                  data:
                    $ref: "#/components/schemas/User"
    put:
      security:
        - Auth: []
      tags:
        - "User API"
      description: "Update User by id"
      summary: "Update User by id"
      parameters:
        - name: "UserId"
          in: "path"
          description: "User Id"
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCreateOrUpdate"
      responses:
        "200":
          description: "Success create User"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  code:
                    type: "number"
                  status:
                    type: "string"
                  data:
                    $ref: "#/components/schemas/User"
    delete:
      security:
        - Auth: []
      tags:
        - "User API"
      description: "Delete User by id"
      summary: "Delete User by id"
      parameters:
        - name: "UserId"
          in: "path"
          description: "User Id"
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "Success delete User"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  code:
                    type: "number"
                  status:
                    type: "string"
  /devices:
    get:
      security:
        - Auth: []
      tags:
        - "Device API"
      description: "List all devices"
      summary: "List all devices"
      responses:
        "200":
          description: "Success get all devices"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  code:
                    type: "number"
                  status:
                    type: "string"
                  data:
                    type: "array"
                    items:
                      $ref: "#/components/schemas/Device"
    post:
      security:
        - Auth: []
      tags:
        - "Device API"
      description: "Create new device"
      summary: "Create new device"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeviceCreateOrUpdate"
      responses:
        "200":
          description: "Success create device"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  code:
                    type: "number"
                  status:
                    type: "string"
                  data:
                    $ref: "#/components/schemas/Device"
  /devices/{DeviceId}:
    get:
      security:
        - Auth: []
      tags:
        - "Device API"
      description: "Get device by id"
      summary: "Get device by id"
      parameters:
        - name: "DeviceId"
          in: "path"
          description: "Device Id"
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "Success get device"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  code:
                    type: "number"
                  status:
                    type: "string"
                  data:
                    $ref: "#/components/schemas/Device"
    put:
      security:
        - Auth: []
      tags:
        - "Device API"
      description: "Update device by id"
      summary: "Update device by id"
      parameters:
        - name: "DeviceId"
          in: "path"
          description: "Device Id"
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeviceCreateOrUpdate"
      responses:
        "200":
          description: "Success update device"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  code:
                    type: "number"
                  status:
                    type: "string"
                  data:
                    $ref: "#/components/schemas/Device"
    delete:
      security:
        - Auth: []
      tags:
        - "Device API"
      description: "Delete device by id"
      summary: "Delete device by id"
      parameters:
        - name: "DeviceId"
          in: "path"
          description: "Device Id"
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "Success delete device"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  code:
                    type: "number"
                  status:
                    type: "string"

components:
  securitySchemes:
    Auth:
      type: apiKey
      in: header
      name: "X-API-Key"
      description: "Authetication for User API"
  schemas:
    User:
      type: "object"
      properties:
        user_id:
          type: "string"
        username:
          type: "string"
        name:
          type: "string"
        devices:
          type: "array"
          items:
            $ref: "#/components/schemas/Device"
    UserCreateOrUpdate:
      type: "object"
      properties:
        username:
          type: "string"
        password:
          type: "string"
        name:
          type: "string"
    Device:
      type: "object"
      properties:
        device_id:
          type: "string"
        generic_access_device_name:
          type: "string"
        device_information_serial_number:
          type: "string"
        device_information_firmware_revision:
          type: "string"
        device_information_software_revision:
          type: "string"
        device_information_manufacturer_name:
          type: "string"
        user_id:
          type: "string"
    DeviceCreateOrUpdate:
      type: "object"
      properties:
        generic_access_device_name:
          type: "string"
        device_information_serial_number:
          type: "string"
        device_information_firmware_revision:
          type: "string"
        device_information_software_revision:
          type: "string"
        device_information_manufacturer_name:
          type: "string"
        user_id:
          type: "string"
