openapi: "3.0.3"
info:
  title: Health Tracker RESTful API
  description: "API Spec for Health Tracker RESTful API"
  version: "1.0"
servers:
  - url: https://localhost:3108/api
paths:
  /users:
    get:
      security:
        - Auth: []
      tags:
        - "User API"
      description: "List all users"
      summary: "List all users"
      responses:
        "200":
          description: "Success get all users"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: "number"
                  status:
                    type: string
                  data:
                    type: "array"
                    items:
                      $ref: "#/components/schemas/User"
    post:
      security:
        - Auth: []
      tags:
        - "User API"
      description: "Create new User"
      summary: "Create new User"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCreateOrUpdate"
      responses:
        "200":
          description: "Success create User"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: "number"
                  status:
                    type: string
                  data:
                    $ref: "#/components/schemas/User"
  /users/{UserId}:
    get:
      security:
        - Auth: []
      tags:
        - "User API"
      description: "Get User by id"
      summary: "Get User by id"
      parameters:
        - name: "UserId"
          in: "path"
          description: "User Id"
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "Success get user"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: "number"
                  status:
                    type: string
                  data:
                    $ref: "#/components/schemas/User"
    put:
      security:
        - Auth: []
      tags:
        - "User API"
      description: "Update User by id"
      summary: "Update User by id"
      parameters:
        - name: "UserId"
          in: "path"
          description: "User Id"
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCreateOrUpdate"
      responses:
        "200":
          description: "Success create User"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: "number"
                  status:
                    type: string
                  data:
                    $ref: "#/components/schemas/User"
    delete:
      security:
        - Auth: []
      tags:
        - "User API"
      description: "Delete User by id"
      summary: "Delete User by id"
      parameters:
        - name: "UserId"
          in: "path"
          description: "User Id"
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "Success delete User"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: "number"
                  status:
                    type: string
  /devices:
    get:
      security:
        - Auth: []
      tags:
        - "Device API"
      description: "List all devices"
      summary: "List all devices"
      responses:
        "200":
          description: "Success get all devices"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: "number"
                  status:
                    type: string
                  data:
                    type: "array"
                    items:
                      $ref: "#/components/schemas/Device"
    post:
      security:
        - Auth: []
      tags:
        - "Device API"
      description: "Create new device"
      summary: "Create new device"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Device"
      responses:
        "200":
          description: "Success create device"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: "number"
                  status:
                    type: string
                  data:
                    $ref: "#/components/schemas/Device"
  /devices/{DeviceId}:
    get:
      security:
        - Auth: []
      tags:
        - "Device API"
      description: "Get device by id"
      summary: "Get device by id"
      parameters:
        - name: "DeviceId"
          in: "path"
          description: "Device Id"
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "Success get device"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: "number"
                  status:
                    type: string
                  data:
                    $ref: "#/components/schemas/Device"
    put:
      security:
        - Auth: []
      tags:
        - "Device API"
      description: "Update device by id"
      summary: "Update device by id"
      parameters:
        - name: "DeviceId"
          in: "path"
          description: "Device Id"
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Device"
      responses:
        "200":
          description: "Success update device"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: "number"
                  status:
                    type: string
                  data:
                    $ref: "#/components/schemas/Device"
    delete:
      security:
        - Auth: []
      tags:
        - "Device API"
      description: "Delete device by id"
      summary: "Delete device by id"
      parameters:
        - name: "DeviceId"
          in: "path"
          description: "Device Id"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Success delete device"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: "number"
                  status:
                    type: string
  /workout-data:
    get:
      security:
        - Auth: []
      tags:
        - "Workout Data API"
      description: "List all workout data"
      summary: "List all workout data"
      responses:
        "200":
          description: "Success get all workout data"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: "number"
                  status:
                    type: string
                  data:
                    type: "array"
                    items:
                      $ref: "#/components/schemas/WorkoutData"
    post:
      security:
        - Auth: []
      tags:
        - "Workout Data API"
      description: "Create new workout data"
      summary: "Create new workout data"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WorkoutDataCreateOrUpdate"
      responses:
        "200":
          description: "Success create workout data"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: "number"
                  status:
                    type: string
                  data:
                    $ref: "#/components/schemas/WorkoutData"
  /workout-data/{WorkoutDataId}:
    get:
      security:
        - Auth: []
      tags:
        - "Workout Data API"
      description: "Get workout data by id"
      summary: "Get workout data by id"
      parameters:
        - name: "WorkoutDataId"
          in: "path"
          description: "Workout Data Id"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Success get workout data"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: "number"
                  status:
                    type: string
                  data:
                    $ref: "#/components/schemas/WorkoutData"
    delete:
      security:
        - Auth: []
      tags:
        - "Workout Data API"
      description: "Delete workout data by id"
      summary: "Delete workout data by id"
      parameters:
        - name: "WorkoutDataId"
          in: "path"
          description: "Workout Data Id"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Success delete workout data"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: "number"
                  status:
                    type: string

components:
  securitySchemes:
    Auth:
      type: apiKey
      in: header
      name: "X-API-Key"
      description: "Authetication for User API"
  schemas:
    User:
      type: object
      properties:
        user_id:
          type: string
        username:
          type: string
        name:
          type: string
        devices:
          type: "array"
          items:
            $ref: "#/components/schemas/Device"
    UserCreateOrUpdate:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        name:
          type: string
    Device:
      type: object
      properties:
        device_id:
          type: string
        device_name:
          type: string
        manufacturer_name:
          type: string
        local_name:
          type: string
        user_id:
          type: string
    WorkoutData:
      type: object
      properties:
        workout_data_id:
          type: string
        workout_data_type:
          type: string
        total_steps:
          type: number
        total_distance:
          type: number
        total_calories:
          type: number
        heart_rate_average:
          type: number
        pace:
          type: number
        duration:
          type: number
        created_at:
          type: string
        device_id:
          type: string
    WorkoutBatchData:
      type: object
      properties:
        total_steps:
          type: number
        total_distance:
          type: number
        total_calories:
          type: number
        heart_rate:
          type: number
        created_at:
          type: string
    WorkoutDataCreateOrUpdate:
      type: object
      properties:
        workout_data_type:
          type: string
        device_id:
          type: string
        duration:
          type: number
        pace:
          type: number
        workout_batch_data:
          type: array
          items:
            $ref: "#/components/schemas/WorkoutBatchData"
